language: go
cache:
  directories:
  - ".taxi-cache/"
before_install:
  - openssl aes-256-cbc -K $encrypted_d4cd1c66d4ec_key -iv $encrypted_d4cd1c66d4ec_iv -in .dockercfg.enc -out .dockercfg -d
install:
- go get -d -v ./... && go build -v ./...
script:
- go test ./taxi
- go build main.go
- "./main install"
- ./main test "./taxi info"

after_success:
- ./main pushtag grahamc/taxi:latest
after_script:
- ./main cleanup

env:
  global:
  - DOCKER_HOST="tcp://docker-builds-us-west-2.cfy.io:2376"
  - secure: EwGDkHdEoI1cgl5FCVqYRwt7oyH4JcwnOAaSYBQmqvX3fX8rN3jPVY1w3cydVSw2z+TGVNe9wtBMBQA4Nw9LMCZNXPZm6IV6lCL+r6d/7xI7RAI79UtKhVs5k2DYyR6LCj3u22RMvTcDcA9oDpz0o44oToeqb3jdfYAm13Ye/XE=
